
executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p s_logs/{rule} &&
  sbatch
    --partition=c-frigon
    --account=ctb-frigon
    --constraint=genoa
    --cpus-per-task=10
    --mem=500G
    --job-name={rule}-{wildcards}
    --output=s_logs/{wildcards}-%j.out
    --time=96:00:00
    --parsable
cluster-generic-cancel-cmd: "scancel"
cluster-generic-status-cmd: status-sacct.sh  # permet a snakemake de connaître le status des job slurm
restart-times: 6 # permet de ressoumettre les jobs qui ont échoués
max-jobs-per-second: 0.1     # Cela peut être utile pour éviter de surcharger le cluster avec trop de soumissions simultanées.
max-status-checks-per-second: 30    #  limiter le nombre total de vérification d'état de tous les jobs
latency-wait: 60    # attendre un certain temps pour que les fichiers soient visibles en cas de MissingFileExeption error
jobs: 14     # le maximum de jobs qui peuvent être roulés en parallèle
keep-going: True    # pour continuer à exécuter les règles qui sont independantes d'une règle qui a échoué
rerun-incomplete: True
printshellcmds: True