project:
    name: Info-Crue CMIP6
    version: 1.0.0
    description: Jeux de données CMIP6 corrigés pour Info-Crue
    id: ic6

tasks:
  #- initialize_pcat
  - regrid
  - simproperties
  - train_qm
  - adjust_qm
  - train_ex
  - adjust_ex
  - clean_up
  - final_zarr


ids:
    - A10_RCP45_R41_qc

dask:
    client:
        dashboard_address: 6785
        # silence_logs: 50
    array.slicing.split_large_chunks: False

logging:
    formatters:
        default:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class : logging.StreamHandler
            formatter: default
            level : DEBUG
    loggers:
        workflow:
            level: INFO
            handlers: [console]



#consider calling this reference or something?
custom:
    encoding:
        tasmax:
            dtype: float32
        tasmin:
            dtype: float32
        pr:
            dtype: float32
    regions:
        test1:
            name: test1
            method: bbox
            bbox:
                lon_bnds: [ -81, -78 ]
                lat_bnds: [ 42, 46 ]
    stack_drop_nans: &stack
        True
    chunks:
        lat: 2 # test
        lon: 2 # test
        loc: 10 # test
        time: -1
    out_chunks:
        lat: 2 # test
        lon: 2 # test
        time: 4year
    future_period:
        - '2071'
        - '2100'
    ref_period : &ref_period
        - '1971'
        - '2002'
    sim_period: &sim_period
        - '1956' # cut the first 5 years to have the 40 year window fit well in the extreme pr bias correction
        - '2100'
        #- '2050'
        #- '2080'

extraction:
    reference:
        search_data_catalogs:
            variables_and_timedeltas:
                tasmax: 1D
                tasmin: 1D
                pr: 1D
            allow_resampling: False
            allow_conversion: True
            periods : *ref_period
        extract_dataset:
            xr_open_kwargs:
                drop_variables:
                    - height
                    - time_vectors
    simulations:
        search_data_catalogs: &search
            variables_and_timedeltas:
                tasmax: 1D
                tasmin: 1D
                pr: 1D
            allow_conversion: True
            allow_resampling: False
            periods : *sim_period
        extract_dataset:
            xr_combine_kwargs:
                combine_attrs: override
            xr_open_kwargs:
                drop_variables:
                    - time_vectors
                    - height

regrid:
    regridder_kwargs:
        extrap_method: inverse_dist
        locstream_out: *stack
        reuse_weights: False

rechunk:
    worker_mem: 2GB


biasadjust_qm:
    variables:
        tasmin:
            training_args:
                reference_period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                xclim_train_args:
                    kind: "+"
                    nquantiles: 50
            adjusting_args:
                simulation_period: *sim_period
                xclim_adjust_args:
                    detrend: 3
        tasmax:
            training_args:
                reference_period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                xclim_train_args:
                    kind: "+"
                    nquantiles: 50
            adjusting_args:
                simulation_period: *sim_period
                xclim_adjust_args:
                    detrend: 3
        pr:
            training_args:
                reference_period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                jitter_under:
                    thresh: 0.05 mm d-1
                xclim_train_args:
                    kind: "*"
                    nquantiles: 50
            adjusting_args:
                simulation_period: *sim_period
                xclim_adjust_args:
                    detrend: 3


biasadjust_ex:
    moving_yearly_window:
        window: 40
        step: 15
    variables:
        pr:
            training_args:
                reference_period: *ref_period
                method: ExtremeValues
                jitter_under:
                    thresh: 0.05 mm d-1
                group: False
                xclim_train_args:
                    cluster_thresh: 1 mm d-1
                    q_thresh: 0.95

            adjusting_args:
                simulation_period: *sim_period


clean_up:
    search_data_catalogs: *search
    final_attrs_names:
        - bias_adjustment
        - cell_methods
        - coordinates
        - history
        - long_name
        - standard_name
        - units
    attrs:
        global:
            Conventions: CF-1.9
            title: Info-Crue CMIP6 - {sim_id} - Region {region_name}
            institution: Ouranos
            source: |
                CHANGE THIS
                Regridded on the grid of ERA5-Land, then bias-adjusted with detrended
                quantile mapping on a day-of-year basis with a window of 31 days, LOESS
                detrending and 50 quantiles. The reference was ERA5-Land over the
                1981-2010 period. Tasmax, dtr and pr were adjusted, tasmin was computed
                from tasmax and dtr after the adjustment.
            redistribution: Redistribution prohibited. For internal use only.
            version: "1.0.0"
        tasmax:
            standard_name: air_temperature
            long_name: Maximal daily temperature
            cell_methods: "time: maximum within days"
        tasmin:
            standard_name: air_temperature
            long_name: Minimal daily temperature
            cell_methods: "time: minimum within days"
        pr:
            standard_name: precipitation_flux
            long_name: Mean daily precipitation flux
            cell_methods: "time: mean within days"


scr_utils:
    measure_time:
        cpu: True
    send_mail:
        to: lavoie.juliette@ouranos.ca
    subject: Info-Crue CMIP6
    send_mail_on_exit:
        msg_ok: Toutes les étapes demandées ont été complétées.
        msg_err: Une erreur est survenue durant le traitement.
        on_error_only: True