project:
    name: Info-Crue CMIP6
    version: 1.0.0
    description: Jeux de données CMIP6 corrigés pour Info-Crue
    id: ic6

tasks:
  - initialize_pcat
  - makeref
  - regrid
  - simproperties
  - train_qm
  - adjust_qm
  - train_ex
  - adjust_ex
  - clean_up
  - final_zarr
  - scenproperties
  - check_up


ids:
  #- CMIP6_ScenarioMIP_NOAA-GFDL_GFDL-ESM4_EXPERIMENT_r1i1p1f1_gr1
    #- CMIP6_ScenarioMIP_BCC_BCC-CSM2-MR_EXPERIMENT_r1i1p1f1_gn
    # downloaded and complete  (20)
    #['CMIP6_ScenarioMIP_AS-RCEC_TaiESM1_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_BCC_BCC-CSM2-MR_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_CAS_FGOALS-g3_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_CCCma_CanESM5_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_CMCC_CMCC-ESM2_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_CNRM-CERFACS_CNRM-CM6-1_EXPERIMENT_r1i1p1f2_gr', 'CMIP6_ScenarioMIP_CNRM-CERFACS_CNRM-ESM2-1_EXPERIMENT_r1i1p1f2_gr', 'CMIP6_ScenarioMIP_CSIRO-ARCCSS_ACCESS-CM2_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_CSIRO_ACCESS-ESM1-5_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_DKRZ_MPI-ESM1-2-HR_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_EXPERIMENT_r1i1p1f1_gr', 'CMIP6_ScenarioMIP_INM_INM-CM5-0_EXPERIMENT_r1i1p1f1_gr1', 'CMIP6_ScenarioMIP_IPSL_IPSL-CM6A-LR_EXPERIMENT_r1i1p1f1_gr', 'CMIP6_ScenarioMIP_MIROC_MIROC6_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_MOHC_UKESM1-0-LL_EXPERIMENT_r1i1p1f2_gn', 'CMIP6_ScenarioMIP_MPI-M_MPI-ESM1-2-LR_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_MRI_MRI-ESM2-0_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_NCC_NorESM2-LM_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_NCC_NorESM2-MM_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_NIMS-KMA_KACE-1-0-G_EXPERIMENT_r1i1p1f1_gr', 'CMIP6_ScenarioMIP_NOAA-GFDL_GFDL-ESM4_EXPERIMENT_r1i1p1f1_gr1']
    # in the TCR likely range #https://zenodo.org/record/6476375#.YnVQNNPMJhE (14)
   ['CMIP6_ScenarioMIP_BCC_BCC-CSM2-MR_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_CAS_FGOALS-g3_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_CMCC_CMCC-ESM2_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_CNRM-CERFACS_CNRM-ESM2-1_EXPERIMENT_r1i1p1f2_gr', 'CMIP6_ScenarioMIP_CSIRO-ARCCSS_ACCESS-CM2_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_CSIRO_ACCESS-ESM1-5_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_DKRZ_MPI-ESM1-2-HR_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_INM_INM-CM5-0_EXPERIMENT_r1i1p1f1_gr1', 'CMIP6_ScenarioMIP_MIROC_MIROC6_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_MPI-M_MPI-ESM1-2-LR_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_MRI_MRI-ESM2-0_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_NCC_NorESM2-LM_EXPERIMENT_r1i1p1f1_gn', 'CMIP6_ScenarioMIP_NIMS-KMA_KACE-1-0-G_EXPERIMENT_r1i1p1f1_gr', 'CMIP6_ScenarioMIP_NOAA-GFDL_GFDL-ESM4_EXPERIMENT_r1i1p1f1_gr1']


experiments: &experiments
    - ssp245
    - ssp370

dask:
    client:
        dashboard_address: 6785
        # silence_logs: 50
    array.slicing.split_large_chunks: False

logging:
    formatters:
        default:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class : logging.StreamHandler
            formatter: default
            level : DEBUG
    loggers:
        workflow:
            level: INFO
            handlers: [console]



custom:
    encoding:
        tasmax:
            dtype: float32
        tasmin:
            dtype: float32
        pr:
            dtype: float32
    regions:
#       test1:
#            name: test1
#            method: bbox
#            bbox:
#                lon_bnds: [ -81, -78 ]
#                lat_bnds: [ 42, 46 ]
        qc:
            name: qc
            method: bbox
            bbox:
                lon_bnds: [ -83, -56 ]
                lat_bnds: [ 42, 63 ]
    stack_drop_nans: &stack
        True
    chunks:
#        lat: 2 # test
#        lon: 2 # test
#        loc: 10 # test
        lat: 15
        lon: 15
        loc: 50
        time: -1
    out_chunks:
#        lat: 2 # test
#        lon: 2 # test
        lat: 30
        lon: 30
        time: 4year
    future_period:
        - '2071'
        - '2100'
    ref_period : &ref_period
        - '1991'
        - '2000'
    sim_period: &sim_period
        - '1956'
        - '2100'
    check_period:
      - '1981'
      - '1982'
    calendar: noleap


extraction:
    reference:
        search_data_catalogs:
            variables_and_timedeltas:
                tasmax: 1D
                tasmin: 1D
                pr: 1D
            allow_resampling: False
            allow_conversion: False
            periods : *ref_period
            other_search_criteria:
                project: &ref_project
                    "era5-land"
                processing_level: ["raw"]
        extract_dataset: {}
    simulations:
        search_data_catalogs:
            variables_and_timedeltas:
                tasmax: 1D
                tasmin: 1D
                pr: 1D
            match_hist_and_fut: True
            allow_conversion: False
            allow_resampling: False
            other_search_criteria:
                processing_level: "raw"
                mip_era: 'CMIP6'
                experiment: *experiments
        extract_dataset:
            periods : *sim_period
            xr_combine_kwargs:
              combine_attrs: override
            xr_open_kwargs:
              drop_variables:
                - height
    ref_project: *ref_project

regrid:
    regridder_kwargs:
        extrap_method: inverse_dist
        locstream_out: *stack
        reuse_weights: False

biasadjust_qm:
    variables:
        tasmin:
            training_args:
                reference_period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                xclim_train_args:
                    kind: "+"
                    nquantiles: 50
            adjusting_args:
                simulation_period: *sim_period
                xclim_adjust_args:
                    detrend: 3
        tasmax:
            training_args:
                reference_period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                xclim_train_args:
                    kind: "+"
                    nquantiles: 50
            adjusting_args:
                simulation_period: *sim_period
                xclim_adjust_args:
                    detrend: 3
        pr:
            training_args:
                reference_period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                jitter_under:
                    thresh: 0.05 mm d-1
                xclim_train_args:
                    kind: "*"
                    nquantiles: 50
            adjusting_args:
                simulation_period: *sim_period
                xclim_adjust_args:
                    detrend: 3

biasadjust_ex:
    moving_yearly_window:
        window: 40
        step: 15
    variables:
        pr:
            training_args:
                reference_period: *ref_period
                method: ExtremeValues
                jitter_under:
                    thresh: 0.05 mm d-1
                group: False
                xclim_train_args:
                    cluster_thresh: 1 mm d-1
                    q_thresh: 0.95

            adjusting_args:
                simulation_period: *sim_period


clean_up:
    search_data_catalogs:
      variables_and_timedeltas:
        tasmax: 1D
        tasmin: 1D
        pr: 1D
    final_attrs_names:
        - bias_adjustment
        - cell_methods
        - coordinates
        - history
        - long_name
        - standard_name
        - units
    attrs:
        global:
            Conventions: CF-1.9
            title: Info-Crue CMIP6 - {sim_id} - Region {region_name}
            institution: Ouranos
            source: |
                Regridded on the grid of ERA5-Land, then bias-adjusted with detrended
                quantile mapping on a day-of-year basis with a window of 31 days, 3rd degree polynomial
                detrending and 50 quantiles. The reference was ERA5-Land over the
                1991-2010 period. There is a second bias adjustement for pr's extreme values.
            redistribution: Redistribution prohibited. For internal use only.
            version: "1.0.0"
        tasmax:
            standard_name: air_temperature
            long_name: Maximal daily temperature
            cell_methods: "time: maximum within days"
        tasmin:
            standard_name: air_temperature
            long_name: Minimal daily temperature
            cell_methods: "time: minimum within days"
        pr:
            standard_name: precipitation_flux
            long_name: Mean daily precipitation flux
            cell_methods: "time: mean within days"

rechunk:
    worker_mem: 2GB

scr_utils:
    measure_time:
        cpu: True
    send_mail:
        to: lavoie.juliette@ouranos.ca
    subject: Info-Crue CMIP6
    send_mail_on_exit:
        msg_ok: Toutes les étapes demandées ont été complétées.
        msg_err: Une erreur est survenue durant le traitement.
        on_error_only: True