project:
    name: reproduce_ESPO-R
    version: 1.0.0
    description: Reproduce ESPO-R calculations with xscen tools.
    id: rer

tasks:
  #- initialize_pcat
  - makeref
  - regrid
  - rechunk
  - simproperties
  - train
  - adjust
  - clean_up
  - final_zarr
  - scenproperties
  - check_up
  - concat

ids:
    - CNRM-CM5_CRCM5-OUR_rcp85_NAM-22i
    #- HadGEM2-ES_WRF_rcp85_NAM-22i
    #- MPI-ESM-LR_CRCM5-OUR_rcp85_NAM-22i
    #- GEMatm-MPI_CRCM5-UQAM_rcp85_NAM-22i
    #- ['CNRM-CM5_CRCM5-OUR_rcp85_NAM-22i', 'CanESM2_CRCM5-OUR_rcp45_NAM-22i', 'CanESM2_CRCM5-OUR_rcp85_NAM-22i', 'CanESM2_CRCM5-UQAM_rcp45_NAM-44i', 'CanESM2_CRCM5-UQAM_rcp85_NAM-22i', 'CanESM2_CRCM5-UQAM_rcp85_NAM-44i', 'CanESM2_CanRCM4_rcp45_NAM-22i', 'CanESM2_CanRCM4_rcp45_NAM-44i', 'CanESM2_CanRCM4_rcp85_NAM-22i', 'CanESM2_CanRCM4_rcp85_NAM-44i', 'CanESM2_RCA4_rcp45_NAM-44i', 'CanESM2_RCA4_rcp85_NAM-44i', 'EC-EARTH_HIRHAM5_rcp45_NAM-44i', 'EC-EARTH_HIRHAM5_rcp85_NAM-44i', 'EC-EARTH_RCA4_rcp45_NAM-44i', 'EC-EARTH_RCA4_rcp85_NAM-44i', 'GEMatm-Can_CRCM5-UQAM_rcp85_NAM-22i', 'GEMatm-Can_CRCM5-UQAM_rcp85_NAM-44i', 'GEMatm-MPI_CRCM5-UQAM_rcp85_NAM-22i', 'GEMatm-MPI_CRCM5-UQAM_rcp85_NAM-44i', 'GFDL-ESM2M_CRCM5-OUR_rcp45_NAM-22i', 'GFDL-ESM2M_CRCM5-OUR_rcp85_NAM-22i', 'GFDL-ESM2M_RegCM4_rcp85_NAM-22i', 'GFDL-ESM2M_RegCM4_rcp85_NAM-44i', 'GFDL-ESM2M_WRF_rcp85_NAM-22i', 'GFDL-ESM2M_WRF_rcp85_NAM-44i', 'HadGEM2-ES_RegCM4_rcp85_NAM-22i', 'HadGEM2-ES_RegCM4_rcp85_NAM-44i', 'HadGEM2-ES_WRF_rcp85_NAM-22i', 'HadGEM2-ES_WRF_rcp85_NAM-44i', 'MPI-ESM-LR_CRCM5-OUR_rcp85_NAM-22i', 'MPI-ESM-LR_CRCM5-UQAM_rcp45_NAM-44i', 'MPI-ESM-LR_CRCM5-UQAM_rcp85_NAM-22i', 'MPI-ESM-LR_CRCM5-UQAM_rcp85_NAM-44i', 'MPI-ESM-LR_RegCM4_rcp85_NAM-22i', 'MPI-ESM-LR_RegCM4_rcp85_NAM-44i', 'MPI-ESM-LR_WRF_rcp85_NAM-22i', 'MPI-ESM-LR_WRF_rcp85_NAM-44i', 'MPI-ESM-MR_CRCM5-UQAM_rcp85_NAM-22i', 'MPI-ESM-MR_CRCM5-UQAM_rcp85_NAM-44i'])


dask:
    client:
        dashboard_address: 6787
        # silence_logs: 50
    array.slicing.split_large_chunks: False

logging:
    formatters:
        default:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class : logging.StreamHandler
            formatter: default
            level : DEBUG
    loggers:
        workflow:
            level: INFO
            handlers: [console]



#consider calling this reference or something?
custom:
    maximal_calendar: &mcal
        noleap
    encoding:
        tasmax:
            dtype: float32
        tasmin:
            dtype: float32
        dtr:
            dtype: float32
        pr:
            dtype: float32
    regions:
#        test3:
#            name: test3
#            method: bbox
#            bbox:
#                lon_bnds: [ -80, -79 ]
#                lat_bnds: [ 44.7, 45 ]
#        test2:
#            name: test2
#            method: bbox
#            bbox:
#                lon_bnds: [ -80, -79 ]
#                lat_bnds: [ 44.2, 44.6 ]
#        test1:
#            name: test1
#            method: bbox
#            bbox:
#                lon_bnds: [ -80, -79 ]
#                lat_bnds: [ 44, 44.2 ]
        north:
            name: north
            method: bbox
            bbox:
                lon_bnds: [-147.55, -52.65]
                lat_bnds: [74.25, 59.25]
        middle:
            name: middle
            method: bbox
            bbox:
                lon_bnds: [-147.55, -52.65]
                lat_bnds: [59.25, 44.25]
        south:
            name: south
            method: bbox
            bbox:
                lon_bnds: [-147.55, -52.65]
                lat_bnds: [44.25, 19.25]
    stack_drop_nans: &stack
        True
    chunks:
        lat: 20
        lon: 20
        loc: 60 # for 120 Mo chunks (~35 chunks in qc)
#        lat: 2 # test
#        lon: 2 # test
#        loc: 10 # test
        time: -1
    out_chunks:
#        lat: 2 # test
#        lon: 2 # test
        lat: 50
        lon: 50
        time: 4year
    future_period:
        - '2071'
        - '2100'
    ref_period : &ref_period
        - '1981'
        - '2010'
    sim_period: &sim_period
        - '1951'
        - '2100'

extraction:
    reference:
        search_data_catalogs:
            variables_and_timedeltas:
                tasmax: 1D
                dtr: 1D
                tasmin: 1D # we keep it in order to do the checkups and be able to compare beginning and end
                pr: 1D
            allow_resampling: False
            allow_conversion: True
            periods : *ref_period
            other_search_criteria:
                source: ["ERA5-Land"]
                processing_level: ["raw"]
        extract_dataset:
            xr_open_kwargs:
                drop_variables:
                    - time_vectors
                    - ts
    simulations:
        search_data_catalogs:
            variables_and_timedeltas:
                tasmax: 1D
                tasmin: 1D # we keep it in order to do the checkups and be able to compare beginning and end
                dtr: 1D
                pr: 1D
            match_hist_and_fut: True
            allow_conversion: True
            allow_resampling: False
            periods : *sim_period
            other_search_criteria:
                processing_level: ["raw"]
        extract_dataset:
            xr_combine_kwargs:
                combine_attrs: override
            xr_open_kwargs:
                drop_variables:
                    - time_vectors
                    - ts

regrid:
    regridder_kwargs:
        extrap_method: inverse_dist
        locstream_out: *stack
        reuse_weights: False

rechunk:
    worker_mem: 2GB


biasadjust:
    variables:
        dtr:
            training_args:
                reference_period: *ref_period
                maximal_calendar: *mcal
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                xclim_train_args:
                    kind: "*"
                    nquantiles: 50
            adjusting_args:
                simulation_period: *sim_period
                xclim_adjust_args:
                    detrend:
                        LoessDetrend:
                            f: 0.2
                            niter: 1
                            d: 0
                            weights: tricube
                    interp: nearest
                    extrapolation: constant
        tasmax:
            training_args:
                reference_period: *ref_period
                maximal_calendar: *mcal
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                xclim_train_args:
                    kind: "+"
                    nquantiles: 50
            adjusting_args:
                simulation_period: *sim_period
                xclim_adjust_args:
                    detrend:
                        LoessDetrend:
                            f: 0.2
                            niter: 1
                            d: 0
                            weights: tricube
                    interp: nearest
                    extrapolation: constant
        pr:
            training_args:
                reference_period: *ref_period
                maximal_calendar: *mcal
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                adapt_freq:
                    thresh: 1 mm d-1
                jitter_under:
                    thresh: 0.01 mm d-1
                xclim_train_args:
                    kind: "*"
                    nquantiles: 50
            adjusting_args:
                simulation_period: *sim_period
                xclim_adjust_args:
                    detrend:
                        LoessDetrend:
                            f: 0.2
                            niter: 1
                            d: 0
                            weights: tricube
                    interp: nearest
                    extrapolation: constant

clean_up:
    final_attrs_names:
        - bias_adjustment
        - cell_methods
        - coordinates
        - history
        - long_name
        - standard_name
        - units
    attrs:
        global:
            Conventions: CF-1.9
            title: ESPO-R v1.0.0 - {sim_id} - Region {region_name}
            institution: Ouranos
            source: |
                Regridded on the grid of ERA5-Land, then bias-adjusted with detrended
                quantile mapping on a day-of-year basis with a window of 31 days, LOESS
                detrending and 50 quantiles. The reference was ERA5-Land over the
                1981-2010 period. Tasmax, dtr and pr were adjusted, tasmin was computed
                from tasmax and dtr after the adjustment.
            redistribution: Redistribution prohibited. For internal use only.
            version: "1.0.0"
            cat/_data_format_: zarr
        tasmax:
            standard_name: air_temperature
            long_name: Maximal daily temperature
            cell_methods: "time: maximum within days"
        tasmin:
            standard_name: air_temperature
            long_name: Minimal daily temperature
            cell_methods: "time: minimum within days"
        pr:
            standard_name: precipitation_flux
            long_name: Mean daily precipitation flux
            cell_methods: "time: mean within days"


scr_utils:
    measure_time:
        cpu: True
    send_mail:
        to: lavoie.juliette@ouranos.ca
    subject: Reproduce ESPO-R
    send_mail_on_exit:
        msg_ok: Toutes les étapes demandées ont été complétées.
        msg_err: Une erreur est survenue durant le traitement.
        on_error_only: True