project:
    name: Info-Crue CMIP6
    version: 1.0.0
    description: Jeux de données CMIP6 corrigés pour Info-Crue
    id: ic6

tasks:
  #- initialize_pcat
  - makeref
  - extract
  - regrid
  - train_qm
  - adjust_qm
  - train_ex
  - adjust_ex
  - clean_up
  - final_zarr
  - diagnostics

ids:
  # in the TCR likely range #https://zenodo.org/record/6476375#.YnVQNNPMJhE (14) #chunking
  # 'CMIP6_ScenarioMIP_BCC_BCC-CSM2-MR_EXPERIMENT_r1i1p1f1_global', # remove because missing a file #None
  - CMIP6_ScenarioMIP_CAS_FGOALS-g3_EXPERIMENT_r1i1p1f1_global # None, but 1 file per year
  - CMIP6_ScenarioMIP_CMCC_CMCC-ESM2_EXPERIMENT_r1i1p1f1_global # [1, 192, 288]
  - CMIP6_ScenarioMIP_CNRM-CERFACS_CNRM-ESM2-1_EXPERIMENT_r1i1p1f2_global # [1, 128, 256]
  - CMIP6_ScenarioMIP_CSIRO-ARCCSS_ACCESS-CM2_EXPERIMENT_r1i1p1f1_global #  [1, 145, 192]
  - CMIP6_ScenarioMIP_CSIRO_ACCESS-ESM1-5_EXPERIMENT_r1i1p1f1_global # [1, 96, 144]
  - CMIP6_ScenarioMIP_DKRZ_MPI-ESM1-2-HR_EXPERIMENT_r1i1p1f1_global # [1, 192, 384] # need to be match with historical from other institution
  - CMIP6_ScenarioMIP_INM_INM-CM5-0_EXPERIMENT_r1i1p1f1_global # [1, 120, 180]
  - CMIP6_ScenarioMIP_MIROC_MIROC6_EXPERIMENT_r1i1p1f1_global # [1, 96, 192]
  - CMIP6_ScenarioMIP_MPI-M_MPI-ESM1-2-LR_EXPERIMENT_r1i1p1f1_global #[1, 96, 192]
  - CMIP6_ScenarioMIP_MRI_MRI-ESM2-0_EXPERIMENT_r1i1p1f1_global #[1, 160, 320]
  - CMIP6_ScenarioMIP_NCC_NorESM2-LM_EXPERIMENT_r1i1p1f1_global #[1, 96, 144]
  - CMIP6_ScenarioMIP_NIMS-KMA_KACE-1-0-G_EXPERIMENT_r1i1p1f1_global #[1, 144, 192] # monthly files need to be removed
  - CMIP6_ScenarioMIP_NOAA-GFDL_GFDL-ESM4_EXPERIMENT_r1i1p1f1_global #[1, 180, 288]

experiments: &experiments
    - ssp245
    - ssp370

custom:
    regions:
        qc:
            name: qc
            method: bbox
            bbox:
                lon_bnds: [ -83, -56 ]
                lat_bnds: [ 42, 63 ]
    stack_drop_nans: &stack
        True
    chunks:
        lat: 15
        lon: 15
        loc: 50
        time: -1
    out_chunks:
        lat: 30
        lon: 30
        time: 4year
    ref_period : &ref_period
        - '1991'
        - '2020'
    sim_period: &sim_period
        - '1956'
        - '2100'
    calendar: noleap # need noleap for ExtremeValues
    encoding:
      tasmax:
        dtype: float32
      tasmin:
        dtype: float32
      dtr:
        dtype: float32
      pr:
        dtype: float32



extract:
    chunks: {'time': 365, 'lat':-1, 'lon':-1}

extraction:
    reference:
        search_data_catalogs:
            variables_and_freqs: &var_and_time
                tasmax: D
                tasmin: D
                pr: D
                dtr: D
            allow_resampling: False
            allow_conversion: True
            periods : *ref_period
            other_search_criteria:
                source: &ref_source
                    "era5-land"
                processing_level: ["raw"]
        extract_dataset: {}
    simulations:
        search_data_catalogs:
            variables_and_freqs:
                *var_and_time
            match_hist_and_fut: True
            allow_conversion: True
            allow_resampling: False
        extract_dataset:
            periods : *sim_period
            xr_combine_kwargs:
              combine_attrs: override
            xr_open_kwargs:
              drop_variables:
                - height
    ref_source: *ref_source

regrid:
    regridder_kwargs:
        method: bilinear
        extrap_method: inverse_dist
        locstream_out: *stack
        reuse_weights: False

biasadjust_qm:
    variables:
        dtr:
            training_args:
                reference_period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                xclim_train_args:
                    kind: "*"
                    nquantiles: 50
            adjusting_args:
                simulation_period: *sim_period
                xclim_adjust_args:
                    detrend:
                        LoessDetrend:
                          f: 0.2
                          niter: 1
                          d: 0
                          weights: tricube
                    interp: nearest
                    extrapolation: constant
                bias_adjust_institution: &b_a_inst
                  Ouranos
                bias_adjust_project: &b_a_pro
                  info-crue CMIP6
        tasmax:
            training_args:
                reference_period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                xclim_train_args:
                    kind: "+"
                    nquantiles: 50
            adjusting_args:
                simulation_period: *sim_period
                xclim_adjust_args:
                  detrend:
                    LoessDetrend:
                      f: 0.2
                      niter: 1
                      d: 0
                      weights: tricube
                  interp: nearest
                  extrapolation: constant
                bias_adjust_institution: *b_a_inst
                bias_adjust_project: *b_a_pro
        pr:
            training_args:
                reference_period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                jitter_under:
                    thresh: 0.05 mm d-1
                xclim_train_args:
                    kind: "*"
                    nquantiles: 50
            adjusting_args:
                simulation_period: *sim_period
                xclim_adjust_args:
                  detrend:
                    LoessDetrend:
                      f: 0.2
                      niter: 1
                      d: 0
                      weights: tricube
                  interp: nearest
                  extrapolation: constant
                bias_adjust_institution: *b_a_inst
                bias_adjust_project: *b_a_pro

biasadjust_ex:
    moving_yearly_window:
        window: 40
        step: 15
    variables:
        pr:
            training_args:
                reference_period: *ref_period
                method: ExtremeValues
                jitter_under:
                    thresh: 0.05 mm d-1
                group: False
                xclim_train_args:
                    cluster_thresh: 1 mm d-1
                    q_thresh: 0.95
            adjusting_args:
                simulation_period: *sim_period
                bias_adjust_institution: *b_a_inst
                bias_adjust_project: *b_a_pro

clean_up:
    search_data_catalogs:
      variables_and_freqs:
        tasmax: D
        tasmin: D
        pr: D
      allow_conversion: True
      allow_resampling: False
    final_attrs_names:
        - bias_adjustment
        - cell_methods
        - coordinates
        - history
        - long_name
        - standard_name
        - units
    units:
      tasmax: degC
      tasmin: degC
      pr: mm d-1
    attrs:
        global:
            Conventions: CF-1.9
            title: Info-Crue CMIP6 - {sim_id}
            institution: Ouranos
            Notes: |
                Regridded on the grid of ERA5-Land, then bias-adjusted with detrended
                quantile mapping on a day-of-year basis with a window of 31 days,
                3rd degree polynomial detrending and 50 quantiles.
                There is a second bias adjustement for pr's extreme values.
                Tasmax, dtr and pr were adjusted, tasmin was computed
                from tasmax and dtr after the adjustment.
                The reference was ERA5-Land over the 1991-2010 period.
            redistribution: Redistribution prohibited. For internal use only.
            version: "1.0.0"
        tasmax:
            standard_name: air_temperature
            long_name: Maximal daily temperature
            cell_methods: "time: maximum within days"
        tasmin:
            standard_name: air_temperature
            long_name: Minimal daily temperature
            cell_methods: "time: minimum within days"
        pr:
            standard_name: precipitation_flux
            long_name: Mean daily precipitation flux
            cell_methods: "time: mean within days"

rechunk:
    worker_mem: 2GB

diagnostics:
  properties:
    'mean-tasmax': {'func':sdba.properties.mean, 'var': 'tasmax', 'args': {}}
    'var-tasmax': {'func':sdba.properties.var, 'var': 'tasmax', 'args': {}, 'measure':'ratio'}
    'skewness-tasmax': {'func':sdba.properties.skewness, 'var': 'tasmax', 'args': {}}
    'quantile_98-tasmax': {'func':sdba.properties.quantile, 'var': 'tasmax', 'args': {'q':0.98} }
    'acf-tasmax': {'func':sdba.properties.acf, 'var': 'tasmax', 'args': {}}
    'maximum_length_of_warm_spell': {'func':sdba.properties.spell_length_distribution,'var': 'tasmax', 'args':{'method': 'quantile', 'op': '>=', 'thresh':0.9, 'stat': 'max'}}
    'annual_cycle_amplitude-tasmax': {'func':sdba.properties.annual_cycle_amplitude, 'var': 'tasmax', 'args':  {}}
    'annual_cycle_phase-tasmax': {'func':sdba.properties.annual_cycle_phase, 'var': 'tasmax', 'args': {}, 'measure':'circular_bias' }
    'trend-tasmax': {'func':sdba.properties.trend, 'var': 'tasmax', 'args': {} }
    'quantile_02-tasmin': {'func':sdba.properties.quantile, 'var': 'tasmin', 'args': {'q':0.02} }
    'frost_days': {'func':sdba.properties.relative_frequency, 'var': 'tasmin', 'args': {'op':'>=', 'thresh': '0 degC'} }
    'mean-pr': {'func':sdba.properties.mean, 'var': 'pr', 'args': {}}
    'var-pr': {'func':sdba.properties.var, 'var': 'pr', 'args':  {}, 'measure':'ratio'}
    'skewness-pr': {'func':sdba.properties.skewness, 'var': 'pr', 'args':  {}}
    'quantile_98-pr': {'func':sdba.properties.quantile, 'var': 'pr', 'args': {'q':0.98} }
    'maximum_length_of_dry_spell': {'func':sdba.properties.spell_length_distribution,'var': 'pr', 'args':{'method': 'amount', 'op': '<', 'thresh':'1 mm d-1', 'stat': 'max'}}
    'annual_cycle_amplitude-pr': {'func':sdba.properties.annual_cycle_amplitude, 'var': 'pr', 'args':  {'amplitude_type':'relative'}, 'measure':'ratio'}
    'wet_days_freq': {'func':sdba.properties.relative_frequency, 'var': 'pr', 'args': {'op':'>=', 'thresh': '1 mm d-1'} }
    '20mm_freq': {'func':sdba.properties.relative_frequency, 'var': 'pr', 'args':  {'op':'>=', 'thresh': '20 mm d-1'}}

scr_utils:
    measure_time:
        cpu: True
    send_mail:
        to: lavoie.juliette@ouranos.ca
    subject: Info-Crue CMIP6
    send_mail_on_exit:
        msg_ok: Toutes les étapes demandées ont été complétées.
        msg_err: Une erreur est survenue durant le traitement.
        on_error_only: True

dask:
    client:
        dashboard_address: 6785
    array.slicing.split_large_chunks: False

logging:
    formatters:
        default:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class : logging.StreamHandler
            formatter: default
            level : INFO
        file:
            class: logging.FileHandler
            formatter: default
            level : DEBUG
    loggers:
        xscen:
            propagate: False
            level: INFO
            handlers: [file, console]
