project:
    name: Info-Crue CMIP6
    version: 1.0.0
    description: Jeux de données CMIP6 corrigés pour Info-Crue
    id: ic6

custom:
    bias_adjust_institution: &bias_adjust_institution
      Ouranos
    bias_adjust_project: &bias_adjust_project
      MBCn-EM
    version: &version
      v10
    regions:
      a-EMDNA: 
        name: a-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 42,  50.05 ]
    NOT-USING: #TODO: remove
      b-EMDNA: 
        name: b-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 43.3, 44.25 ]
      c-EMDNA:
        name: c-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 44.3, 45.05 ]
      d-EMDNA:
        name: d-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 45.1, 45.75 ]
      e-EMDNA:
        name: e-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 45.8, 46.45 ]
      f-EMDNA:
        name: f-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 46.5, 47.15 ]
      g-EMDNA:
        name: g-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 47.2, 47.85 ]
      h-EMDNA:
        name: h-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 47.9, 48.55 ]
      i-EMDNA:  
        name: i-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 48.6, 49.25 ]
      j-EMDNA:
        name: j-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 49.3, 50.05 ]
      k-EMDNA:    
        name: k-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 50.1, 50.65 ]
      l-EMDNA:  
        name: l-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 50.7, 51.25 ]
      m-EMDNA:
        name: m-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 51.3, 51.85 ]
      n-EMDNA:
        name: n-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 51.9, 52.45 ]
      o-EMDNA:
        name: o-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 52.5, 53.05 ]
      p-EMDNA:
        name: p-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 53.1, 53.65 ]
      q-EMDNA:
        name: q-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 53.7, 54.25 ]
      r-EMDNA:
        name: r-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 54.3, 54.95 ]
      s-EMDNA:
        name: s-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 55.0, 55.65 ]
      t-EMDNA:
        name: t-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 55.7, 56.55 ]
      u-EMDNA:  
        name: u-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 56.6, 57.45 ]
      v-EMDNA:    
        name: v-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 57.5, 58.45 ]
      w-EMDNA:  
        name: w-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 58.5, 59.55 ]
      x-EMDNA:  
        name: x-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 59.6, 61.05 ]
      y-EMDNA:  
        name: y-EMDNA 
        method: bbox
        lon_bnds: [ -83, -55 ]
        lat_bnds: [ 61.1, 62.95 ]
    full_region: # if this changes, need to change paths with QC in snakefile
      name: QC-EMDNA
      method: bbox
      lon_bnds: [ -83, -55 ]
      lat_bnds: [ 42, 63 ]
    stack_drop_nans: &stack
        True
    working_chunks:
        lat: 15
        lon: 15
        loc: 10
        time: -1
    final_zarr_chunks: 
        lat: 5
        lon: 30
        time: 4year
    concat_chunks: 
        lat: 30
        lon: 30
    sim_chunks:
      time: 365
      lat: -1
      lon: -1
    ref_period : &ref_period # new-ref
      - '1989'
      - '2018'
    sim_period: &sim_period
        - '1951'
        - '2100'
    encoding:
      tasmax:
        dtype: float32
      tasmin:
        dtype: float32
      dtr:
        dtype: float32
      pr:
        dtype: float32
    maximal_calendar: &mcal
      noleap
    align_on:
      year

extraction:
    reference:
        search_data_catalogs:
            variables_and_freqs: &var_and_freq
                tasmax: D
                tasmin: D
                pr: D
                dtr: D
            allow_resampling: False
            allow_conversion: True
            periods : *ref_period
            other_search_criteria:
                source: &ref_source
                  EMDNA
                member: OI
        extract_dataset:
          xr_combine_kwargs: {} # bc of xscen bug
        clean_up:
          to_level: extracted
          variables_and_units:
            tasmax: K
            tasmin: K
    simulation:
        search_data_catalogs:
          variables_and_freqs: *var_and_freq
          match_hist_and_fut: True
          allow_conversion: True
          allow_resampling: False
          periods: *sim_period
          exclusions:
            id:
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp126_r2i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp245_r2i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp370_r2i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp585_r2i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp126_r3i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp245_r3i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp370_r3i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp585_r3i1p1f1_global
              - CMIP6_ScenarioMIP_CAS_FGOALS-g3_ssp126_r2i1p1f1_global
              - CMIP6_ScenarioMIP_CAS_FGOALS-g3_ssp245_r2i1p1f1_global
              - CMIP6_ScenarioMIP_CAS_FGOALS-g3_ssp370_r2i1p1f1_global
              - CMIP6_ScenarioMIP_CAS_FGOALS-g3_ssp585_r2i1p1f1_global
          other_search_criteria:
            processing_level: raw
            #member: r1i1p1f1
            experiment:
              - ssp585
              - ssp245
              - ssp370
              - ssp126
            source:
              # chosen
              - ACCESS-ESM1-5
              - CanESM5
              - EC-Earth3
              - FGOALS-g3
              - IPSL-CM6A-LR
              - KACE-1-0-G
              - MIROC6
              - MRI-ESM2-0
            mip_era: CMIP6
        extract_dataset:
            periods : *sim_period
            xr_combine_kwargs:
              combine_attrs: override
            xr_open_kwargs:
              engine: h5netcdf
              drop_variables:
                - height
                - bnds
                - time_bnds
                - lat_bnds
                - lon_bnds
              chunks:
                lat: 30
                lon: 30
                time: 365

regrid:
  regrid_dataset:
    regridder_kwargs:
      method: bilinear
      extrap_method: inverse_dist
      locstream_out: *stack
      reuse_weights: False
    intermediate_grids:
      reg1:
        cf_grid_2d:
          lon0_b: 274.75
          lon1_b: 305.2
          d_lon: 1
          lat0_b: 39.75
          lat1_b: 64
          d_lat: 1
        regridder_kwargs:
          method: bilinear
          extrap_method: inverse_dist
          locstream_out: False
          reuse_weights: False
      reg2:
        cf_grid_2d:
          lon0_b: 274.74
          lon1_b: 305.2
          d_lon: 0.5
          lat0_b: 39.74
          lat1_b: 64
          d_lat: 0.5
        regridder_kwargs:
          method: bilinear
          extrap_method: inverse_dist
          locstream_out: False
          reuse_weights: False



biasadjust_mbcn:
  train:
    var: #TODO: think about this more, because we have some temperature inversion
      - tasmax
      - dtr
      - pr
    method: MBCn
    period: *ref_period
    group:
      group: 5D
      window: 7
    xsdba_train_args:
      base_kws:
        nquantiles: 50
      n_iter: 20
      adj_kws:
        interp: nearest
        extrapolation: constant
        n_escore: -1
  adjust:
    periods: *sim_period
    xsdba_adjust_args:
      period_dim: period # stacking
      base_kws_vars:
        pr:
          kind: "*"
          jitter_under_thresh_value: "1.1574e-07 kg m^-2 s^-1" #"0.01 mm d-1" #FIXME: when xscen/xsda can handle units correctly
          adapt_freq_thresh: "1.1574e-05 kg m^-2 s^-1" #"1 mm d-1"
        dtr:
          kind: "*"
          jitter_under_thresh_value: "1e-4 K"
        tasmin:
          kind: "+"
        tasmax:
          kind: "+"
      adj_kws:
        interp: nearest
        extrapolation: constant
  attrs:
    processing_level: biasadjusted
    bias_adjust_institution: *bias_adjust_institution
    bias_adjust_project: *bias_adjust_project
    version: *version

clean_up:
  xscen_clean_up:
    to_level: cleaned_up
    variables_and_units:
      tasmax: degC
      tasmin: degC
      pr: mm d-1
    convert_calendar_kwargs:
      calendar: standard
      align_on: year
    missing_by_var:
      tasmax: interpolate
      tasmin: interpolate
      pr: 0
      dtr: interpolate
    maybe_unstack_dict:
      stack_drop_nans: *stack
      dim: loc
      rechunk:
        lat: 15
        lon: 15
        time: -1
    round_var:
      pr: 10
    remove_all_attrs_except:
      global:
        - history
        - "cat:id"
        - "cat:source"
        - "cat:member"
        - "cat:experiment"
        - "cat:institution"
        - "cat:activity"
        - "cat:bias_adjust_project"
        - "cat:bias_adjust_institution"
        - "cat:domain"
        - "cat:mip_era"
        - "cat:type"
      tasmax: &attrs_to_keep
        - bias_adjustment
        - cell_methods
        - coordinates
        - history
        - long_name
        - standard_name
        - units
      tasmin: *attrs_to_keep
      pr: *attrs_to_keep
      dtr: *attrs_to_keep
    add_attrs:
      global:
        Notes: |
          Regridded on the grid of EMDNA, then bias-adjusted with MBCn.
          The reference was EMDNA over the 1989-2018 period.
        version: "v10"
        code: https://github.com/Ouranosinc/info-crue-cmip6/tree/mbcn-stacked
        contact: lavoie.juliette@ouranos.ca
        organisation: Groupe scénarios et services climatiques, Consortium Ouranos, Montréal, QC; www.ouranos.ca
        avertissement : Ouranos ne donne aucune garantie, expresse ou implicite, y compris, mais sans s'y limiter, les garanties de qualité marchande et d'adéquation à un usage particulier. Toutes les responsabilités découlant de la fourniture des informations (y compris toute responsabilité découlant d'une négligence) sont exclues dans toute la mesure permise par la loi.
        license:  Creative Commons Attribution 4.0 International (https://creativecommons.org/licenses/by/4.0/)
      tasmax:
          standard_name: air_temperature
          long_name: Maximal daily temperature
          cell_methods: "time: maximum within days"
      tasmin:
          standard_name: air_temperature
          long_name: Minimal daily temperature
          cell_methods: "time: minimum within days"
      pr:
          standard_name: precipitation_flux
          long_name: Mean daily precipitation flux
          cell_methods: "time: mean within days"
      dtr:
          standard_name: air_temperature
          long_name: Mean diurnal temperature range
          cell_methods: "time range within days"

rechunk:
    worker_mem: 2GB


diagnostics:
  properties_and_measures:
    rechunk: {'lat': 30, 'lon': 30, 'time': -1}
    period: *ref_period
    unstack: False
    change_units_arg:
      tasmax: degC
      tasmin: degC
      pr: mm d-1
      dtr: K
    properties: config/properties_info-crue-6.yml
  health_checks:
    structure:
      coords:
        - lat
        - lon
        - time
      dims:
        - lat
        - lon
        - time
    start_date: "1951-01-01"
    end_date: "2100-12-30"
    variables_and_units:
      tasmax: "°C"
      tasmin: "°C"
      pr: "mm d-1"
      dtr: K 
    cfchecks:
      tasmax:
        cfcheck_from_name: {}
      tasmin:
        cfcheck_from_name: {}
      pr:
        cfcheck_from_name: {}
    freq: D
    flags:
      tasmax:
        temperature_extremely_high:
          thresh: '60 degC'
        tasmax_below_tasmin:
      tasmin:
        temperature_extremely_low:
          thresh: '-70 degC'
      pr:
        negative_accumulation_values:
        very_large_precipitation_events:
          thresh: '300 mm/d'
    return_flags: True
    raise_on:
      - structure
      - start_date
      - end_date
      - variables_and_units
      - cfchecks
      - freq


io:
  save_to_zarr:
    mode: o
    strip_cat_metadata: False #FIXME: when default is changed in xscen

dask:
    client:
        dashboard_address: 6785
    array.slicing.split_large_chunks: False

logging:
  formatters:
    default:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class : logging.StreamHandler
      formatter: default
      level : DEBUG
  loggers:
    xscen:
      propagate: False
      level: INFO
      handlers: [console] 
    workflow:
      propagate: False
      level: INFO
      handlers: [console]
    distributed.worker:
      propagate: False
      level: INFO
      handlers: [console]
    distributed.scheduler:
      propagate: False
      level: INFO
      handlers: [console]
    distributed.nanny:
      propagate: False
      level: DEBUG
      handlers: [console]
    distributed.client:
      propagate: INFO
      level: INFO
      handlers: [console]

tdd:
  xarray_open_kwargs:
    decode_timedelta: False


