project:
    name: Info-Crue CMIP6
    version: 1.0.0
    description: Jeux de données CMIP6 corrigés pour Info-Crue
    id: ic6

tasks:
  - makeref
  - extract
  - regrid
  #- mbcn-30years
  - mbcn-30years-noTMP
  #- npdf-gpies-narval
  - clean_up
  - final_zarr
  - health_checks
  - diagnostics
  - concat

custom:
    delete_in_final_zarr: False
    delete_in_diag: True
    regions:
        a-EMDNA: 
          name: a-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 42, 43 ]
        b-EMDNA: 
          name: b-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 43.05, 44 ]
        c-EMDNA:
          name: c-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 44.05, 45 ]
        d-EMDNA:
          name: d-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 42, 43 ]
        e-EMDNA:
          name: e-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 43.05, 44 ]
        f-EMDNA:
          name: f-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 44.05, 45 ]
        g-EMDNA:
          name: g-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 45.05, 46 ]
        h-EMDNA:
          name: h-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 46.05, 47 ]
        i-EMDNA:  
          name: i-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 47.05, 48 ]
        j-EMDNA:
          name: j-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 48.05, 49 ]
        k-EMDNA:    
          name: k-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 49.05, 50 ]
        l-EMDNA:  
          name: l-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 50.05, 51 ]
        m-EMDNA:
          name: m-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 51.05, 52 ]
        n-EMDNA:
          name: n-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 52.05, 53 ]
        o-EMDNA:
          name: o-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 53.05, 54 ]
        p-EMDNA:
          name: p-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 54.05, 55 ]
        q-EMDNA:
          name: q-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 55.05, 56 ]
        r-EMDNA:
          name: r-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 56.05, 57 ]
        s-EMDNA:
          name: s-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 57.05, 58 ]
        t-EMDNA:
          name: t-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 58.05, 59 ] 
        u-EMDNA:  
          name: u-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 59.05, 60 ]
        v-EMDNA:    
          name: v-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 60.05, 61 ] 
        w-EMDNA:  
          name: w-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 61.05, 62 ]
        x-EMDNA:  
          name: x-EMDNA 
          method: bbox
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 62.05, 63.05 ] 
        # mini-EMDNA: # winner
        #   name: mini-EMDNA 
        #   method: bbox
        #   lon_bnds: [ -83, -55 ]
        #   lat_bnds: [ 42, 43 ]
        # petit-EMDNA:
        #   name: petit-EMDNA 
        #   method: bbox
        #   lon_bnds: [ -83, -55 ]
        #   lat_bnds: [ 42, 45 ]
        # A-EMDNA:
        #   name: A-EMDNA 
        #   method: bbox
        #   lon_bnds: [ -83, -55 ]
        #   lat_bnds: [ 42, 47 ]
        # B-EMDNA:
        #   name: B-EMDNA 
        #   method: bbox
        #   lon_bnds: [ -83, -55 ]
        #   lat_bnds: [ 42, 47 ]
        # QC-EMDNA:
        #   name: QC-EMDNA
        #   method: bbox
        #   lon_bnds: [ -83, -55 ]
        #   lat_bnds: [ 42, 63 ]
        # SUD-EMDNA:
        #   name: SUD-EMDNA
        #   method: bbox
        #   lon_bnds: [ -83, -55 ]
        #   lat_bnds: [ 42, 52 ]
      # QC-test:
      #     name: QC-test
      #     method: bbox
      #     lon_bnds: [ -60, -58 ]
      #     lat_bnds: [ 50, 52 ]
    qc_region:
      name: QC-EMDNA
    stack_drop_nans: &stack
        True
    working_chunks: #chunks
        lat: 15
        lon: 15
        loc: 10 #50 #TODO
        #loc: 50
        time: -1
    final_zarr_chunks: #out_chunks:
        #lat: 30 $TODO: 5
        lat: 5
        lon: 30
        time: 4year
    concat_chunks: 
        lat: 30
        lon: 30
    sim_chunks:
      time: 365
      lat: -1
      lon: -1
    ref_chunk:
      time: -1
    ref_prop_chunk:
      lat: 30
      lon: 30
    ref_period : &ref_period # new-ref
      - '1989'
      - '2018'
    sim_period: &sim_period
        - '1951'
        - '2100'
    encoding:
      tasmax:
        dtype: float32
      tasmin:
        dtype: float32
      dtr:
        dtype: float32
      pr:
        dtype: float32
    maximal_calendar: &mcal
      noleap
    align_on:
      year

extraction:
    reference:
        context:
          client_kw:
            n_workers: 6 # 3
            threads_per_worker: 4
            memory_limit: "15GB"
          measure_time_kw:
            name: makeref
        search_data_catalogs:
            variables_and_freqs: &var_and_freq
                tasmax: D
                tasmin: D
                pr: D
                dtr: D
            allow_resampling: False
            allow_conversion: True
            periods : *ref_period
            other_search_criteria:
                source: &ref_source
                  EMDNA
                member: OI
        extract_dataset:
          xr_combine_kwargs: {} # bc of xscen bug
        clean_up:
          to_level: extracted
          variables_and_units:
            tasmax: K
            tasmin: K
        properties_and_measures:
          period: *ref_period
          unstack: False
          to_level_prop: diag-ref-prop
          change_units_arg:
            tasmax: degC
            tasmin: degC
            pr: mm d-1
    simulation:
        context:
          client_kw:
            n_workers: 4 #2
            threads_per_worker: 5
            memory_limit: "30GB"
          measure_time_kw:
            name: extract
          timeout_kw:
            seconds: 10600
            task: extract
        search_data_catalogs:
          variables_and_freqs: *var_and_freq
          match_hist_and_fut: True
          allow_conversion: True
          allow_resampling: False
          periods: *sim_period
          exclusions:
            id:
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp126_r2i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp245_r2i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp370_r2i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp585_r2i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp126_r3i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp245_r3i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp370_r3i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp585_r3i1p1f1_global
              - CMIP6_ScenarioMIP_CAS_FGOALS-g3_ssp126_r2i1p1f1_global
              - CMIP6_ScenarioMIP_CAS_FGOALS-g3_ssp245_r2i1p1f1_global
              - CMIP6_ScenarioMIP_CAS_FGOALS-g3_ssp370_r2i1p1f1_global
              - CMIP6_ScenarioMIP_CAS_FGOALS-g3_ssp585_r2i1p1f1_global
          other_search_criteria:
            processing_level: raw
            #member: r1i1p1f1
            experiment:
              - ssp585
              - ssp245
              - ssp370
              - ssp126
            source:
              # chosen
              - ACCESS-ESM1-5
              - CanESM5
              - EC-Earth3
              - FGOALS-g3
              - IPSL-CM6A-LR
              - KACE-1-0-G
              - MIROC6
              - MRI-ESM2-0
            mip_era: CMIP6
        extract_dataset:
            periods : *sim_period
            xr_combine_kwargs:
              combine_attrs: override
            xr_open_kwargs:
              engine: h5netcdf
              drop_variables:
                - height
                - bnds
                - time_bnds
                - lat_bnds
                - lon_bnds
              chunks:
                lat: 30
                lon: 30
                time: 365
    ref_source: *ref_source

regrid:
  context:
    client_kw:
      n_workers: 4 #2
      threads_per_worker: 5
      memory_limit: "25GB"
    measure_time_kw:
      name: regrid
  target:
    source: *ref_source
    calendar: noleap
  regrid_dataset:
    regridder_kwargs:
      method: bilinear
      extrap_method: inverse_dist
      locstream_out: *stack
      reuse_weights: False
    intermediate_grids:
      reg1:
        cf_grid_2d:
          lon0_b: 274.75
          lon1_b: 305.2
          d_lon: 1
          lat0_b: 39.75
          lat1_b: 64
          d_lat: 1
        regridder_kwargs:
          method: bilinear
          extrap_method: inverse_dist
          locstream_out: False
          reuse_weights: False
      reg2:
        cf_grid_2d:
          lon0_b: 274.74
          lon1_b: 305.2
          d_lon: 0.5
          lat0_b: 39.74
          lat1_b: 64
          d_lat: 0.5
        regridder_kwargs:
          method: bilinear
          extrap_method: inverse_dist
          locstream_out: False
          reuse_weights: False

biasadjust_mbcn:
  context:
    train:
      client_kw:
        n_workers: 3 
        threads_per_worker: 3
        memory_limit: "130 GB" #"35GB"
      measure_time_kw:
        name: train mbcn
      timeout_kw:
        seconds: 900000
        task: train mcbn
    adjust:
      client_kw:
        n_workers: 6 #3
        threads_per_worker: 3
        memory_limit: "65GB"
      measure_time_kw:
        name: adjust mbcn
      timeout_kw:
        seconds: 10000000
        task: adjust mcbn
    trainadjust:
      measure_time_kw:
        name: train adjust mbcn
      timeout_kw:
        seconds: 10000000
        task: train adjust mcbn
  group:
    group: time.dayofyear
    window: 31
  variable:
    - tasmax
    - pr
    - dtr
  train:
    n_iter: 20
    adj_kws:
      interp: nearest
      extrapolation: constant
      n_escore: -1
  adjust:
    base_kws_vars:
      pr:
        kind: "*"
        jitter_under_thresh_value: "0.01 mm d-1" #TODO: put back
        adapt_freq_thresh: "1 mm d-1"
      dtr:
        kind: "*"
        jitter_under_thresh_value: "1e-4 K"
      tasmax:
        kind: "+"
    adj_kws:
      interp: nearest
      extrapolation: constant
  chunks:
    loc: 10  #TODO
    #loc: 50
    time: -1
  attrs:
    processing_level: biasadjusted
    bias_adjust_institution: Ouranos
    bias_adjust_project: IC6-EM-MBCn

clean_up:
  context:
    client_kw:
      n_workers: 8 #4
      threads_per_worker: 3
      memory_limit: "15GB"
    measure_time_kw:
      name: cleanup
    timeout_kw:
      seconds: 7200
      task: clean_up
  search_data_catalogs:
    variables_and_freqs:
      tasmax: D
      tasmin: D
      pr: D
    allow_conversion: True
    allow_resampling: False
  xscen_clean_up:
    to_level: cleaned_up
    variables_and_units:
      tasmax: degC
      tasmin: degC
      pr: mm d-1
    convert_calendar_kwargs:
      target: standard
      align_on: random
    missing_by_var:
      tasmax: interpolate
      tasmin: interpolate
      pr: [0]
    maybe_unstack_dict:
      stack_drop_nans: *stack
      rechunk:
        lat: 15
        lon: 15
        time: -1
    round_var:
      pr: 10
    remove_all_attrs_except:
      global:
        - '^cat:'
        - history
      tasmax: &attrs_to_keep
        - bias_adjustment
        - cell_methods
        - coordinates
        - history
        - long_name
        - standard_name
        - units
      tasmin: *attrs_to_keep
      pr: *attrs_to_keep
    add_attrs:
      global:
        Notes: |
          Regridded on the grid of EMDNA, then bias-adjusted with MBCn.
          The reference was EMDNA over the 1989-2018 period.
        version: "1.0.0"
        code: https://github.com/Ouranosinc/info-crue-cmip6/tree/mbcn-narval
        contact: lavoie.juliette@ouranos.ca
        organisation: Groupe scénarios et services climatiques, Consortium Ouranos, Montréal, QC; www.ouranos.ca
        avertissement : Ouranos ne donne aucune garantie, expresse ou implicite, y compris, mais sans s'y limiter, les garanties de qualité marchande et d'adéquation à un usage particulier. Toutes les responsabilités découlant de la fourniture des informations (y compris toute responsabilité découlant d'une négligence) sont exclues dans toute la mesure permise par la loi.
        license:  Creative Commons Attribution 4.0 International (https://creativecommons.org/licenses/by/4.0/)
      tasmax:
          standard_name: air_temperature
          long_name: Maximal daily temperature
          cell_methods: "time: maximum within days"
      tasmin:
          standard_name: air_temperature
          long_name: Minimal daily temperature
          cell_methods: "time: minimum within days"
      pr:
          standard_name: precipitation_flux
          long_name: Mean daily precipitation flux
          cell_methods: "time: mean within days"

rechunk:
    worker_mem: 2GB

final_zarr:
  context:
    client_kw:
      n_workers: 6 #3
      threads_per_worker: 3
      memory_limit: "20GB"
    measure_time_kw:
        name: final zarr rechunk


diagnostics:
  context:
    client_kw:
      n_workers: 8
      threads_per_worker: 3
      memory_limit: "5GB"
  steps:
    sim:
      input:
        processing_level:  regridded
      dref_for_measure:
        processing_level: diag-ref-prop
      properties_and_measures:
        rechunk: {'lat': 30, 'lon': 30, 'time': -1}
        period: *ref_period
        unstack: *stack
        change_units_arg:
          tasmax: degC
          tasmin: degC
          pr: mm d-1
    scen:
      input:
        processing_level: final
      dref_for_measure:
        processing_level: diag-ref-prop
      properties_and_measures:
        rechunk: {'lat':30, 'lon':30, 'time':-1}
        period: *ref_period
        unstack: False
  health_checks:
    structure:
      coords:
        - lat
        - lon
        - time
      dims:
        - lat
        - lon
        - time
    start_date: "1951-01-01"
    end_date: "2100-12-30"
    variables_and_units:
      tasmax: "°C"
      tasmin: "°C"
      pr: "mm d-1"
    cfchecks:
      tasmax:
        cfcheck_from_name: {}
      tasmin:
        cfcheck_from_name: {}
      pr:
        cfcheck_from_name: {}
    freq: D
    flags:
      tasmax:
        temperature_extremely_high:
          thresh: '60 degC'
        tasmax_below_tasmin:
      tasmin:
        temperature_extremely_low:
          thresh: '-70 degC'
      pr:
        negative_accumulation_values:
        very_large_precipitation_events:
          thresh: '300 mm/d'
    return_flags: True
    raise_on:
      - structure
      - start_date
      - end_date
      - variables_and_units
      - cfchecks
      - freq




io:
  save_to_zarr:
    mode: o

scripting:
    measure_time:
        cpu: True
    subject: Info-Crue CMIP6
    send_mail_on_exit:
        msg_ok: Toutes les étapes demandées ont été complétées.
        msg_err: Une erreur est survenue durant le traitement.
        on_error_only: True

dask:
    client:
        dashboard_address: 6785
    array.slicing.split_large_chunks: False

logging:
    formatters:
        default:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class : logging.StreamHandler
            formatter: default
            level : INFO
            stream: ext://sys.stdout #needed to have the right color in pycharm
        # file:
        #     class: logging.FileHandler
        #     formatter: default
        #     level : DEBUG
    loggers:
        xscen:
            propagate: False
            level: INFO
            handlers: [console] # file

tdd:
  xarray_open_kwargs:
    decode_timedelta: False
