project:
    name: Info-Crue CMIP6
    version: 1.0.0
    description: Jeux de données CMIP6 corrigés pour Info-Crue
    id: ic6

tasks:
  ####- initialize_pcat
#  - makeref
#  - extract
#  - regrid
##  - ba-MBCn
###  - ba-dOTC
#  - train_qm
#  - adjust_qm
#  - train_ex
#  - adjust_ex
#  - clean_up
#  - final_zarr
#  - diagnostics
#  - individual_wl
  - horizons
#  - deltas
#  - ensembles



custom:
    delete_in_final_zarr: False
    delete_in_diag: True
    regions:
#        QC-TEST2:
#          name: QC-TEST2
#          method: bbox
#          bbox:
#            lon_bnds: [ -83, -55 ]
#            lat_bnds: [ 42, 63 ]
#      test_MBCn50:
#        name: test_MBCn50
#        method: bbox
#        bbox:
#          lon_bnds: [ -72,-70.5 ]
#          lat_bnds: [ 46,47.5 ]
#        qc:
#            name: qc
#            method: bbox
#            bbox:
#                lon_bnds: [ -83, -56 ]
#                lat_bnds: [ 42, 63 ]
#      QC-MBCn50q50i:
#          name: QC-MBCn50q50i
#          method: bbox
#          bbox:
#              lon_bnds: [ -83, -55 ]
#              lat_bnds: [ 42, 63 ]
      QC:
        name: QC
        method: bbox
        bbox:
          lon_bnds: [ -83, -55 ]
          lat_bnds: [ 42, 63 ]
#      east:
#        name: east
#        method: bbox
#        bbox:
#            lon_bnds: [ -55.95, -55 ]
#            lat_bnds: [ 42, 63 ]

    stack_drop_nans: &stack
        True
    chunks:
        lat: 15
#        lon: -1  # east
        lon: 15
        loc: 50
        time: -1
    out_chunks:
        lat: 30
        lon: 30
#        lat: 16 # test
#        lon: 16 #Test
#        lon: 1 # east
        time: 4year
    ref_period : &ref_period
      - '1991'
      - '2020'
    sim_period: &sim_period
        - '1956'
        - '2100'
    encoding:
      tasmax:
        dtype: float32
      tasmin:
        dtype: float32
      dtr:
        dtype: float32
      pr:
        dtype: float32
    maximal_calendar: &mcal
      noleap




extract:
    sim_chunks:
      time: 365
      lat: -1
      lon: -1
    subset_warming_level:
      ignore_member: True
      window: 20
      wl_dim: "+{wl}C"
    ref_chunk :
      time: -1
      lat: 30
      lon: 30
    ref_prop_chunk:
      lat: 30
      lon: 30




extraction:
    reference:
        search_data_catalogs:
            variables_and_freqs: &var_and_freq
                tasmax: D
                tasmin: D
                pr: D
                dtr: D
            allow_resampling: False
            allow_conversion: True
            periods : *ref_period
            other_search_criteria:
                source: &ref_source
                    "ERA5-Land"
        extract_dataset: {}
        properties_and_measures:
          period: *ref_period
          unstack: False
          to_level_prop: diag-ref-prop
          change_units_arg:
            tasmax: degC
            tasmin: degC
            pr: mm d-1
    simulation:
        search_data_catalogs:
          variables_and_freqs: *var_and_freq
          match_hist_and_fut: True
          allow_conversion: True
          allow_resampling: False
          periods: *sim_period
          exclusions:
            id:
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp126_r2i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp245_r2i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp370_r2i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp585_r2i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp126_r3i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp245_r3i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp370_r3i1p1f1_global
              - CMIP6_ScenarioMIP_EC-Earth-Consortium_EC-Earth3_ssp585_r3i1p1f1_global
              - CMIP6_ScenarioMIP_CAS_FGOALS-g3_ssp126_r2i1p1f1_global
              - CMIP6_ScenarioMIP_CAS_FGOALS-g3_ssp245_r2i1p1f1_global
              - CMIP6_ScenarioMIP_CAS_FGOALS-g3_ssp370_r2i1p1f1_global
              - CMIP6_ScenarioMIP_CAS_FGOALS-g3_ssp585_r2i1p1f1_global
          other_search_criteria:
#            member:
#              - r1i1p1f1
            experiment:
              - ssp585
              - ssp245
              - ssp370
              - ssp126
            source:
              # chosen
              - ACCESS-ESM1-5
              - CanESM5
              - EC-Earth3
              - FGOALS-g3
              - IPSL-CM6A-LR
              - KACE-1-0-G
              - MIROC6
              - MRI-ESM2-0
##              #other
#              - UKESM1-0-LL #245,370,558
#              - GFDL-ESM4 #245,370,585
#              - CNRM-CM6-1 # 245,370,585
#              - CNRM-ESM2-1 # 245,370,585
#              - ACCESS-CM2 #126, 245,370,585
#              - MPI-ESM1-2-HR
#              - NorESM2-MM
            mip_era: CMIP6
        extract_dataset:
            periods : *sim_period
            xr_combine_kwargs:
              combine_attrs: override
            xr_open_kwargs:
              drop_variables:
                - height
                - bnds
                - time_bnds
                - lat_bnds
                - lon_bnds
              chunks:
                lat: 50
                lon: 50
                time: 365
    ref_source: *ref_source

regrid:
  target:
    source: *ref_source
    calendar: noleap
  regrid_dataset:
    regridder_kwargs:
      method: bilinear
      extrap_method: inverse_dist
      locstream_out: *stack
      reuse_weights: False
    intermediate_grids:
      reg1:
        cf_grid_2d:
          lon0_b: 274.75
          lon1_b: 305.2
          d_lon: 1
          lat0_b: 39.75
          lat1_b: 64
          d_lat: 1
        regridder_kwargs:
          method: bilinear
          extrap_method: inverse_dist
          locstream_out: False
          reuse_weights: False
      reg2:
        cf_grid_2d:
          lon0_b: 274.74
          lon1_b: 305.2
          d_lon: 0.5
          lat0_b: 39.74
          lat1_b: 64
          d_lat: 0.5
        regridder_kwargs:
          method: bilinear
          extrap_method: inverse_dist
          locstream_out: False
          reuse_weights: False

biasadjust_dOTC:
  adjust: {}
  attrs:
    processing_level: biasadjusted
    bias_adjust_institution: Ouranos
    bias_adjust_project: info-crue-CMIP6

biasadjust_qm:
    variables:
        dtr:
            training_args:
                period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                xclim_train_args:
                    kind: "*"
                    nquantiles: 50
            adjusting_args:
                periods: *sim_period
                xclim_adjust_args:
                    detrend:
                        LoessDetrend:
                          f: 0.2
                          niter: 1
                          d: 0
                          weights: tricube
                    interp: nearest
                    extrapolation: constant
                bias_adjust_institution: &b_a_inst
                  Ouranos
                bias_adjust_project: &b_a_pro
                  info-crue-CMIP6
        tasmax:
            training_args:
                period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                xclim_train_args:
                    kind: "+"
                    nquantiles: 50
            adjusting_args:
                periods: *sim_period
                xclim_adjust_args:
                  detrend:
                    LoessDetrend:
                      f: 0.2
                      niter: 1
                      d: 0
                      weights: tricube
                  interp: nearest
                  extrapolation: constant
                bias_adjust_institution: *b_a_inst
                bias_adjust_project: *b_a_pro
        pr:
            training_args:
                period: *ref_period
                method: DetrendedQuantileMapping
                group:
                    group: time.dayofyear
                    window: 31
                jitter_under:
                    thresh: 0.05 mm d-1
                xclim_train_args:
                    kind: "*"
                    nquantiles: 50
            adjusting_args:
                periods: *sim_period
                xclim_adjust_args:
                  detrend:
                    LoessDetrend:
                      f: 0.2
                      niter: 1
                      d: 0
                      weights: tricube
                  interp: nearest
                  extrapolation: constant
                bias_adjust_institution: *b_a_inst
                bias_adjust_project: *b_a_pro


biasadjust_ex:
    moving_yearly_window:
        window: 40
        step: 15
    variables:
        pr:
            training_args:
                period: *ref_period
                method: ExtremeValues
                jitter_under:
                    thresh: 0.05 mm d-1
                group: False
                xclim_train_args:
                    cluster_thresh: 1 mm d-1
                    q_thresh: 0.95
            adjusting_args:
                periods: *sim_period
                bias_adjust_institution: *b_a_inst
                bias_adjust_project: *b_a_pro
clean_up:
  search_data_catalogs:
    variables_and_freqs:
      tasmax: D
      tasmin: D
      pr: D
    allow_conversion: True
    allow_resampling: False
  xscen_clean_up:
    to_level: cleaned_up
    variables_and_units:
      tasmax: degC
      tasmin: degC
      pr: mm d-1
    convert_calendar_kwargs:
      target: standard
      align_on: random
    missing_by_var:
      tasmax: interpolate
      tasmin: interpolate
      pr: [0]
    maybe_unstack_dict:
      stack_drop_nans: *stack
      rechunk:
        lat: 15
        lon: 15
        time: -1
    round_var:
      pr: 10
    remove_all_attrs_except:
      global:
        - '^cat:'
        - history
      tasmax: &attrs_to_keep
        - bias_adjustment
        - cell_methods
        - coordinates
        - history
        - long_name
        - standard_name
        - units
      tasmin: *attrs_to_keep
      pr: *attrs_to_keep
    add_attrs:
      global:
        Notes: |
          Regridded on the grid of ERA5-Land, then bias-adjusted with detrended
          quantile mapping on a day-of-year basis with a window of 31 days,
          LOESS detrending and 50 quantiles.
          There is a second bias adjustement for pr's extreme values.
          Tasmax, dtr and pr were adjusted, tasmin was computed
          from tasmax and dtr after the adjustment.
          The reference was ERA5-Land over the 1991-2010 period.
        version: "1.0.0"
      tasmax:
          standard_name: air_temperature
          long_name: Maximal daily temperature
          cell_methods: "time: maximum within days"
      tasmin:
          standard_name: air_temperature
          long_name: Minimal daily temperature
          cell_methods: "time: minimum within days"
      pr:
          standard_name: precipitation_flux
          long_name: Mean daily precipitation flux
          cell_methods: "time: mean within days"

rechunk:
    worker_mem: 2GB


diagnostics:
  sim:
    input:
      processing_level:  regridded
    dref_for_measure:
      processing_level: diag-ref-prop
    properties_and_measures:
      period: *ref_period
      unstack: *stack
      rechunk: {'lat':30, 'lon':30, 'time':-1}
      change_units_arg:
        tasmax: degC
        tasmin: degC
        pr: mm d-1
  scen:
    input:
      processing_level: final
    dref_for_measure:
      processing_level: diag-ref-prop
    properties_and_measures:
      rechunk: {'lat':30, 'lon':30, 'time':-1}
      period: *ref_period
      unstack: False



individual_wl:
  input:
    processing_level: final
    source: EC-Earth3
    domain: qc
  chunks: {'time':-1, 'lat':30, 'lon':30}
  wl:
    - 1.5
    - 2
    - 3

horizons:
  input:
    processing_level: final
    domain: qc
  chunks: {'time':-1, 'lat':30, 'lon':30}
  periods:
    - ['2081', '2100']
    - *ref_period
  produce_horizon:
    to_level: horizon{period0}-{period1}

deltas:
  input:
    processing_level:
      - +1.5C
      - +2C
      - +3C
      - horizon2081-2100
  reference:
    processing_level: horizon1991-2020

ensembles:
  inputs:
    delta-+1.5C-selection:
      processing_level: delta-+1.5C
      source: ['ACCESS-ESM1-5','CanESM5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    delta-+2C-selection:
      processing_level: delta-+2C
      source: [ 'ACCESS-ESM1-5','CanESM5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    delta-+3C-selection:
      processing_level: delta-+3C
      source: [ 'ACCESS-ESM1-5','CanESM5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    delta-ssp126-2081-2100-selection:
      processing_level: delta-horizon2081-2100
      experiment: ssp126
      source: [ 'ACCESS-ESM1-5','CanESM5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    delta-ssp245-2081-2100-selection:
      processing_level: delta-horizon2081-2100
      experiment: ssp245
      source: [ 'ACCESS-ESM1-5','CanESM5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    delta-ssp370-2081-2100-selection:
      processing_level: delta-horizon2081-2100
      experiment: ssp370
      source: [ 'ACCESS-ESM1-5','CanESM5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    delta-ssp585-2081-2100-selection:
      processing_level: delta-horizon2081-2100
      experiment: ssp585
      source: [ 'ACCESS-ESM1-5','CanESM5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    delta-+1.5C-all:
      processing_level: delta-+1.5C
    delta-+2C-all:
      processing_level: delta-+2C
    delta-+3C-all:
      processing_level: delta-+3C
    delta-ssp126-2081-2100-all:
      processing_level: delta-horizon2081-2100
      experiment: ssp126
    delta-ssp245-2081-2100-all:
      processing_level: delta-horizon2081-2100
      experiment: ssp245
    delta-ssp370-2081-2100-all:
      processing_level: delta-horizon2081-2100
      experiment: ssp370
    delta-ssp585-2081-2100-all:
      processing_level: delta-horizon2081-2100
      experiment: ssp585
    delta-ssp245-2081-2100-selectionNoCanESM5:
      processing_level: delta-horizon2081-2100
      experiment: ssp245
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    delta-ssp370-2081-2100-selectionNoCanESM5:
      processing_level: delta-horizon2081-2100
      experiment: ssp370
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    delta-ssp370-2081-2100-selectionNoCanESM5r1:
      processing_level: delta-horizon2081-2100
      experiment: ssp370
      member: r1i1p1f1
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    delta-ssp370-2081-2100-allr1:
      processing_level: delta-horizon2081-2100
      experiment: ssp370
      member: r1i1p1f1
    delta-ssp245-2081-2100-selectionNoCanESM5r1:
      processing_level: delta-horizon2081-2100
      experiment: ssp245
      member: r1i1p1f1
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    delta-ssp245-2081-2100-allr1:
      processing_level: delta-horizon2081-2100
      experiment: ssp245
      member: r1i1p1f1
  generate_weights:
    independence_level: GCM
  ensemble_stats:
    common_attrs_only: True
    statistics:
      ensemble_mean_std_max_min:
      ensemble_percentiles:
  diffs:
    +1.5C-selectionVSall:
      first:
        processing_level: delta-+1.5C-selection
      second:
        processing_level: delta-+1.5C-all
    +2C-selectionVSall:
      first:
        processing_level: delta-+2C-selection
      second:
        processing_level: delta-+2C-all
    +3C-selectionVSall:
      first:
        processing_level: delta-+3C-selection
      second:
        processing_level: delta-+3C-all
    ssp126-2081-2100-selectionVSall:
      first:
        processing_level: delta-ssp126-2081-2100-selection
      second:
        processing_level: delta-ssp126-2081-2100-all
    ssp245-2081-2100-selectionVSall:
      first:
        processing_level: delta-ssp245-2081-2100-selection
      second:
        processing_level: delta-ssp245-2081-2100-all
    ssp370-2081-2100-selectionVSall:
      first:
        processing_level: delta-ssp370-2081-2100-selection
      second:
        processing_level: delta-ssp370-2081-2100-all
    ssp585-2081-2100-selectionVSall:
      first:
        processing_level: delta-ssp585-2081-2100-selection
      second:
        processing_level: delta-ssp585-2081-2100-all
    ssp245-2081-2100-selectionNoCanESM5VSall:
      first:
        processing_level: delta-ssp245-2081-2100-selectionNoCanESM5
      second:
        processing_level: delta-ssp245-2081-2100-all
    ssp370-2081-2100-selectionNoCanESM5VSall:
      first:
        processing_level: delta-ssp370-2081-2100-selectionNoCanESM5
      second:
        processing_level: delta-ssp370-2081-2100-all
    ssp245-2081-2100-selectionNoCanESM5r1VSallr1:
      first:
        processing_level: delta-ssp245-2081-2100-selectionNoCanESM5r1
      second:
        processing_level: delta-ssp245-2081-2100-allr1
    ssp370-2081-2100-selectionNoCanESM5r1VSallr1:
      first:
        processing_level: delta-ssp370-2081-2100-selectionNoCanESM5r1
      second:
        processing_level: delta-ssp370-2081-2100-allr1
  pvalues:
    p-ssp370-2081-2100-selectionVSall:
      first:
        processing_level: delta-horizon2081-2100
        experiment: ssp370
        source: [ 'ACCESS-ESM1-5','CanESM5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
      second:
        processing_level: delta-horizon2081-2100
        experiment: ssp370
    p-+3C-selectionVSall:
      first:
        processing_level: delta-+3C
        source: [ 'ACCESS-ESM1-5','CanESM5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
      second:
        processing_level: delta-+3C




io:
  save_to_zarr:
    mode: o

scripting:
    measure_time:
        cpu: True
    send_mail:
        to: lavoie.juliette@ouranos.ca
    subject: Info-Crue CMIP6
    send_mail_on_exit:
        msg_ok: Toutes les étapes demandées ont été complétées.
        msg_err: Une erreur est survenue durant le traitement.
        on_error_only: True

dask:
    client:
        dashboard_address: 6785
    array.slicing.split_large_chunks: False

logging:
    formatters:
        default:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class : logging.StreamHandler
            formatter: default
            level : INFO
        file:
            class: logging.FileHandler
            formatter: default
            level : DEBUG
    loggers:
        xscen:
            propagate: False
            level: INFO
            handlers: [file, console]

tdd:
  xarray_open_kwargs:
    decode_timedelta: False
