# Config for comparison

tasks:
  #- initialize_pcat
  - horizons
  - deltas
  - regrid
  - ensembles

project:
    name: Info-Crue CMIP6 comparison
    version: 1.0.0
    description: Comparaison de version de Info-Crue
    id: ic6c

horizons:
  input:
    processing_level:
      - final
      - biasadjusted
    experiment:
      - ssp245
      - rcp45
    activity:
      - CMIP5 # TODO: should I include only CMIP5 or also CORDEX?
      - ScenarioMIP
    domain:
      - QC
      - QC-RDRS
      - QC-EMDNA
    source:
      #hausfather
      - ACCESS-ESM1-5
      #- CanESM5
      - EC-Earth3
      - FGOALS-g3
      - IPSL-CM6A-LR
      - KACE-1-0-G
      - MIROC6
      - MRI-ESM2-0
      # CMIP5
      - ACCESS1.0
      - ACCESS1.3
      - BCC-CSM1.1(m)
      - BCC-CSM1.1
      - BNU-ESM
      - CMCC-CM
      - CMCC-CMS
      - CNRM-CM5
      - FGOALS-g2
      - GFDL-ESM2G
      - GFDL-ESM2M
      - GISS-E2-H
      - IPSL-CM5A-MR
      - IPSL-CM5B-LR
      - INM-CM4
      - MIROC-ESM-CHEM
      - MIROC-ESM
      - MRI-CGCM3
      - NorESM1-M
      - CanESM2
      - CSIRO-Mk3.6.0
      - GFDL-CM3
      - GISS-E2-R # this one is supposed to have 2 members, but only one was found on our disks "nomenclature cQ2 ne permettait pas de distinguer ces 2 membres (r6i1p1 et r6i1p3)... Je sens qu'un des deux a juste été écrasé à un moment"
      - IPSL-CM5A-LR
      - MIROC5
      - MPI-ESM-LR
      - MPI-ESM-MR
  chunks: {'time':-1, 'lat':30, 'lon':30}
  periods:
    - ['2071', '2100']
    - ['1991','2020']


deltas:
  input:
    processing_level:
      - comp-horizon2071-2100
    domain:
      - QC-RDRS
      - QC-EMDNA
      - QC-E5L
      - QC-CM5
  reference:
    processing_level: comp-horizon1991-2020

regrid:
  input:
    processing_level:
      - comp-horizon2071-2100
      - comp-horizon1991-2020
      - delta-comp-horizon2071-2100
    domain:
      - QC-EMDNA
      - QC-E5L
      - QC-CM5
  target:
    domain: QC-RDRS
    processing_level: comp-horizon2071-2100
    id: CMIP6_ScenarioMIP_MIROC_MIROC6_ssp245_r1i1p1f1_global # just choose a random one
  regrid_dataset:
    regridder_kwargs:
      method: bilinear
      extrap_method: inverse_dist
      locstream_out: False
      reuse_weights: False


ensembles:
  ensemble_stats:
    common_attrs_only: True
    statistics:
      ensemble_percentiles:
  groups:
    RDRS: # basic groups don't include CanESM5
        domain: QC-RDRS
        source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    EMDNA:
      domain: QC-EMDNA
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    E5L:
      domain: QC-E5L
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    EMDNA2rdrs:
      domain: QC-EMDNA2rdrs
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    E5L2rdrs:
      domain: QC-E5L2rdrs
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    CM5:
      domain: QC-CM52rdrs
    CM6:
      domain:
        - QC-RDRS
        - QC-EMDNA2rdrs
        - QC-E5L2rdrs
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]


dask:
    client:
        dashboard_address: 6785
    array.slicing.split_large_chunks: False

logging:
    formatters:
        default:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class : logging.StreamHandler
            formatter: default
            level : INFO
    loggers:
        xscen:
            propagate: False
            level: INFO
            handlers: [ console]

io:
  save_to_zarr:
    mode: o

scripting:
    measure_time:
        cpu: True
    subject: Info-Crue CMIP6
    send_mail_on_exit:
        msg_ok: Toutes les étapes demandées ont été complétées.
        msg_err: Une erreur est survenue durant le traitement.
        on_error_only: True

tdd:
  xarray_open_kwargs:
    decode_timedelta: False