# Config for comparison

tasks:
  #- initialize_pcat
  - horizons
  - deltas
  - regrid
  - ensembles

project:
    name: Info-Crue CMIP6 comparison
    version: 1.0.0
    description: Comparaison de version de Info-Crue
    id: ic6c

horizons:
  input:
    processing_level:
      - final
      - biasadjusted
    experiment:
      - ssp245
      - rcp45
    activity:
      - CMIP5 # GISS-E2-R is missing one member, but we decided that it is ok for the comp.
      - CORDEX
      - ClimEx #TDOD: not in 585 ? verify
      - ScenarioMIP
    domain:
      - QC
      - QC-44
      - QC-22
      - QC-11
      - QC-RDRS
      - QC-EMDNA
    source:
      #hausfather
      - ACCESS-ESM1-5
      #- CanESM5
      - EC-Earth3
      - FGOALS-g3
      - IPSL-CM6A-LR
      - KACE-1-0-G
      - MIROC6
      - MRI-ESM2-0
        #atlas2022
      - ACCESS1.0
      - ACCESS1.3
      - BCC-CSM1.1
      - BCC-CSM1.1(m)
      - BNU-ESM
      - CCCma-CanRCM4
      - CMCC-CESM
      - CMCC-CM
      - CMCC-CMS
      - CNRM-CM5
      - CSIRO-Mk3.6.0
      - CanESM2
      - DMI-HIRHAM5
      - FGOALS-g2
      - GFDL-CM3
      - GFDL-ESM2G
      #- GFDL-ESM2M #TODO: put back
      - GISS-E2-H
      - GISS-E2-R  # this one is supposed to have 2 members, but only one was found on our disks "nomenclature cQ2 ne permettait pas de distinguer ces 2 membres (r6i1p1 et r6i1p3)... Je sens qu'un des deux a juste été écrasé à un moment"
      #- INM-CM4
      - IPSL-CM5A-LR
      - IPSL-CM5A-MR
      - IPSL-CM5B-LR
      - ISU-RegCM4
      - MIROC-ESM
      - MIROC-ESM-CHEM
      #- MIROC5 #TODO: put back
      - MPI-ESM-LR # UQAM-CRCM5 piloté par LR est juste un doublon de MR
      - MPI-ESM-MR
      - MRI-CGCM3
      - MRI-ESM1
      - NorESM1-M
      - OURANOS-CRCM5
      - SMHI-RCA4
      - UQAM-CRCM5
  chunks: {'time':-1, 'lat':30, 'lon':30}
  periods:
    - ['2071', '2100']
    - ['1991','2020']


deltas:
  input:
    processing_level:
      - comp-horizon2071-2100
    domain:
      - QC-RDRS
      - QC-EMDNA
      - QC-E5L
      - QC-CM5
      - QC-44
      - QC-22
      - QC-11
  reference:
    processing_level: comp-horizon1991-2020

regrid:
  input:
    processing_level:
      - comp-horizon2071-2100
      - comp-horizon1991-2020
      - delta-comp-horizon2071-2100
    domain:
      - QC-EMDNA
      - QC-E5L
      - QC-CM5
      - QC-44
      - QC-22
      - QC-11
  target:
    domain: QC-RDRS
    processing_level: comp-horizon2071-2100
    xrfreq: AS-JAN
    id: CMIP6_ScenarioMIP_MIROC_MIROC6_ssp245_r1i1p1f1_global # just choose a random one
  regrid_dataset:
    regridder_kwargs:
      method: bilinear
      extrap_method: inverse_dist
      locstream_out: False
      reuse_weights: False


ensembles:
  ensemble_stats:
    common_attrs_only: True
    statistics:
      ensemble_percentiles:
  groups:
    RDRS: # basic groups don't include CanESM5 #21
        domain: QC-RDRS
        source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    EMDNA: #21
      domain: QC-EMDNA
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    E5L: #21
      domain: QC-E5L
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    EMDNA2rdrs: #21
      domain: QC-EMDNA2rdrs
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    E5L2rdrs: #21
      domain: QC-E5L2rdrs
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]
    CM5: #51
      domain: QC-CM52rdrs
      activity: CMIP5
    ATLAS2022: #62
      domain:
        - QC-CM52rdrs
        - QC-442rdrs
        - QC-222rdrs
        - QC-112rdrs
    CM6: # 63
      domain:
        - QC-RDRS
        - QC-EMDNA2rdrs
        - QC-E5L2rdrs
      source: [ 'ACCESS-ESM1-5','EC-Earth3','FGOALS-g3','IPSL-CM6A-LR', 'KACE-1-0-G','MIROC6','MRI-ESM2-0' ]


dask:
    client:
        dashboard_address: 6785
    array.slicing.split_large_chunks: False

logging:
    formatters:
        default:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class : logging.StreamHandler
            formatter: default
            level : INFO
    loggers:
        xscen:
            propagate: False
            level: INFO
            handlers: [ console]

io:
  save_to_zarr:
    mode: o

scripting:
    measure_time:
        cpu: True
    subject: Info-Crue CMIP6
    send_mail_on_exit:
        msg_ok: Toutes les étapes demandées ont été complétées.
        msg_err: Une erreur est survenue durant le traitement.
        on_error_only: True

tdd:
  xarray_open_kwargs:
    decode_timedelta: False